pipeline{


  agent any

  stages{


    stage("run front end"){


      steps{

        echo 'executing npm . ..'
        nodejs('Node22.11.0'){

           sh 'npm install'

        }
       


      }




    }








  }











}
